-- GSL codegen
-- !! Autogenerated !! Do not edit, your changes will be overwritten !!

function gen(n)
	return coroutine.wrap(function ()
	for i = 2, n do
		coroutine.yield(i)
	end
end)
end
function filter(p, g)
	return coroutine.wrap(function ()
	for n in g do
		if n % p ~= 0 then
			coroutine.yield(n)
		end
	end
end)
end
local N = 100
local x = gen(N)
while 1 do
	local n = x()
	if n == null then
		break
	end
	print(n)
	local x = filter(n, x)
end
