-- GSL codegen
-- !! Autogenerated !! Do not edit, your changes will be overwritten !!

local a = 123
if a == 20 + 3 + 2 * 50 then
	print('math is mathing')
	print(20 + 3 + 2 * 50, a)
else
	print('math broke :(')
end
